### ISSUE TITLE
Error with Prettier extension in Visual Studio Code

### ISSUE THREAD

**Issue by szape89** [Gudahtt/prettier-plugin-sort-json#117] opened 2022-12-01 19:07 UTC
Hi @Gudahtt,
First of all, thank you for your work!
I have the configurations in the project's root folder, your plugin is configured in .prettierrc file like this:
`"jsonSortOrder": ".prettierjsonsortrc"`
When I run prettier from the command line, everything works fine, but in VSCode there is an error when formatting with the Prettier extension:
`ENOENT: no such file or directory, open '.prettierjsonsortrc'`
The error points to this line in the source: https://github.com/Gudahtt/prettier-plugin-sort-json/blob/main/src/index.ts#L203
Is there a proper way to configure the plugin to work both via CLI and VSCode extension that I'm not seeing or this might be an unsupported feature or even a bug? My guess would be it could happen that when using the Prettier extension in VSCode, not the project root is used, unlike with the CLI.
Thanks in advance!

**Comment by Gudahtt** [comment] 2022-12-02 02:41
Thanks for the report! I can reproduce this as well.

Currently this plugin is assuming that the sort order path is relative to the current working directory. The most popular Prettier extension for VSCode seems to run commands from my home directory rather than the project directory, so it's using the wrong path to find this file. I'll find a way to fix this.

**Comment by Gudahtt** [comment] 2022-12-02 04:08
There don't seem to be any especially reliable ways of resolving the path. Prettier does provide a way to find the prettier configuration file, but if the file is specified using a CLI flag that wouldn't work.

Instead I'm going to convert this option from a path to a string. The sort order will be specified as a JSON string instead of in a separate file.

**Closed** 2022-12-20 14:41 UTC
Labels: bug

**Comment by Gudahtt** [comment] 2022-12-20 22:55
@szape89 This should be fixed in v1.0.0. Let me know if this solves the problem!

**Comment by szape89** [comment] 2022-12-21 07:05
@Gudahtt Thank you for the fix! It addresses the original issue but brings up another one. If Prettier configurations are stored in a JSON then I think there is no way to configure it without an error.

If I configure it like this:
`"jsonSortOrder": '{ "placeThisFirst": null, "/^[^\\d+]/": "lexical", "/^\\d+/": "numeric" }'`
Then the plugin works, but I get JSON parsing errors for the Prettier config file.

If I configure it like this:
`"jsonSortOrder": "{ \"placeThisFirst\": null, \"/^[^\\d+]/\": \"lexical\", \"/^\\d+/\": \"numeric\" }"`
Then the Prettier config file can be parsed but the sort order option cannot be and the plugin does not work.

Does this mean that JS or YAML should be used to configure Prettier or is this something that can be fixed?

Thanks in advance!

**Comment by Gudahtt** [comment] 2022-12-21 12:55
It looks like that snippet isn't escaped properly; the backslashes in the keys need to be double-escaped unfortunately. e.g.

`"jsonSortOrder": "{ \"placeThisFirst\": null, \"/^[^\\\\d+]/\": \"lexical\", \"/^\\\\d+/\": \"numeric\" }"`

With the escaping, the `\\\\d` resolves to the string `\\d`, which resolves to the regex `\d`.

Thanks for highlighting this issue though! I can add a warning in the README about it.

**Comment by Gudahtt** [comment] 2022-12-21 14:25
The readme has been updated with a note about this here: https://github.com/Gudahtt/prettier-plugin-sort-json/pull/136

**Comment by szape89** [comment] 2022-12-22 09:50
@Gudahtt Good catch, it works, thanks again!
